//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOBClass
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ninadbEntities : DbContext
    {
        public ninadbEntities()
            : base("name=ninadbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MOBClientes> MOBClientes { get; set; }
        public virtual DbSet<MOBPromociones> MOBPromociones { get; set; }
        public virtual DbSet<MOBPromocionesGeneradas> MOBPromocionesGeneradas { get; set; }
        public virtual DbSet<MOBUbicaciones> MOBUbicaciones { get; set; }
    
        public virtual ObjectResult<spMOBSeleccionarPromocionAleatoria_Result> spMOBSeleccionarPromocionAleatoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMOBSeleccionarPromocionAleatoria_Result>("spMOBSeleccionarPromocionAleatoria");
        }
    }
}
