//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOBClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOBPromociones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOBPromociones()
        {
            this.MOBPromocionesGeneradas = new HashSet<MOBPromocionesGeneradas>();
        }
    
        public int id_promocion { get; set; }
        public string descripcion { get; set; }
        public string especificaciones { get; set; }
        public int cantidad_premios { get; set; }
        public string imagen_nombre { get; set; }
        public int premios_restantes { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public decimal Valor { get; set; }
        public string Codigo { get; set; }
        public bool ProductoGratis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOBPromocionesGeneradas> MOBPromocionesGeneradas { get; set; }
    }
}
