//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOBClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOBPromocionesGeneradas
    {
        public int id_promocion_generada { get; set; }
        public int id_promocion { get; set; }
        public int id_cliente { get; set; }
        public int id_ubicacion { get; set; }
        public Nullable<System.DateTime> fecha_canje { get; set; }
        public Nullable<bool> entregado { get; set; }
        public Nullable<int> id_ticket { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> idSucursal { get; set; }
    
        public virtual MOBClientes MOBClientes { get; set; }
        public virtual MOBPromociones MOBPromociones { get; set; }
        public virtual MOBUbicaciones MOBUbicaciones { get; set; }
    }
}
