//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOBClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOBUbicaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOBUbicaciones()
        {
            this.MOBPromocionesGeneradas = new HashSet<MOBPromocionesGeneradas>();
            this.MOBClientes = new HashSet<MOBClientes>();
        }
    
        public int id_ubicacion { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string codigoURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOBPromocionesGeneradas> MOBPromocionesGeneradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOBClientes> MOBClientes { get; set; }
    }
}
